 source 'https://rubygems.org'

 gem 'sinatra'
 gem 'activesupport'
 gem 'net-ldap'
 gem 'dm-core'
 gem 'dm-migrations'
 gem 'dm-sqlite-adapter'
 gem 'dm-validations'
 gem 'dm-timestamps'
 gem 'attr_encrypted'
 gem 'sinatra-contrib'
 gem 'thin'
 gem 'rest-client'
 gem 'ruby-debug-ide'
 gem 'debase'
 gem 'debase-ruby_core_source'